### ISSUE TITLE
migrate with email server

### ISSUE THREAD

**Issue by sIiiS** [magenx/MASC-M#10]
Is this possible migrate this file with your email server configuration in this link (https://github.com/magenx/magenx-email-server)?

**Comment by magenx** [comment]
you need to move your email server?

**Comment by sIiiS** [comment]
I want use your email server with this file in one package
I have not anything in my server

**Comment by magenx** [comment]
you are free to go, install magento server then email server.

**Comment by sIiiS** [comment]
are they compatible with together ?

**Comment by magenx** [comment]
yes.
