### ISSUE TITLE
Turpentine Varnish FPC??

### ISSUE THREAD

**Issue by sIiiS** [magenx/MASC-M#11]
Hi, I can not see any installation and configuration "Turpentine Varnish FPC" in the script...!

**Comment by magenx** [comment]
right, i guess you just need to do:
```./mage install community Nexcessnet_Turpentine ```
then varnish will pick this up.

**Comment by sIiiS** [comment]
Yes I know, but don't have any configuration related to the script ?

**Comment by magenx** [comment]
Turpentine configuration is inside of Magento admin

**Comment by sIiiS** [comment]
Which one is better for this script configuration?
Turpentine Varnish FPC or LestiFPC?
