### ISSUE TITLE
Request: add mod_spdy and mod_pagespeed

### ISSUE THREAD

**Issue by seansan** [magenx/MASC-M#14]
Hi, can we add mod_spdy and mod_pagespeed via the script? we have some good experience with it. Maybe as an option yes/no?

Most sites nowadays run on SSL only - would be great if we could at least add mod_spdy

Superb ;)

**Comment by magenx** [comment]
there is no apache in here.

**Comment by seansan** [comment]
We mean the nginx variants of course

is SPDY included in nginx configuration?
