### ISSUE TITLE
Unable to access Magento Connect Manager

### ISSUE THREAD

**Issue by mrlerch** [magenx/MASC-M#16]
Hello. I recently installed Magento 1.9.1 with your script. Thank you very much for making this available. I am however running into some issues. I am unable to load Magento Connect Manager. I see that inside the nginx config file for the magento store you are blocking all access to the "downloader" directory. But even if I allow access to the downloader directory by removing it from this deny all block, it only downloads the index.php file inside downloader/ as some sort of BIN file instead of processing it.

Then I saw inside the nginx config file for the magento store the block where location ~ \.php$. So technically it should include the sub directories for .php file execution?

Can you help me shed some light on this? Maybe someone has an idea?

Thanks,

Martin

**Comment by magenx** [comment]
you have to use ./mage in magento root folder.

```
./mage
Connect commands available:
===========================
channel-add          Add a Channel
channel-alias        Specify an alias to a channel name
channel-delete       Remove a Channel From the List
channel-info         Retrieve Information on a Channel
channel-login        Connects and authenticates to remote channel server
channel-logout       Logs out from the remote channel server
clear-cache          Clear Web Services Cache
config-get           Show One Setting
config-help          Show Information About Setting
config-set           Change Setting
config-show          Show All Settings
convert              Convert old magento PEAR package to new format
download             Download Package
info                 Display information about a package
install              Install Package
install-file         Install Package Archive File
list-available       List Available Packages
list-channels        List Available Channels
list-files           List Files In Installed Package
list-installed       List Installed Packages In The Default Channel
list-upgrades        List Available Upgrades
package              Build Package
package-dependencies Show package dependencies
package-prepare      Show installation information of package
sync                 Synchronize Manually Installed Packages
sync-pear            Synchronize already Installed Packages by pear
uninstall            Un-install Package
upgrade              Upgrade Package
upgrade-all          Upgrade All Packages
```

https://www.yireo.com/blog/1294-magento-15-mage-command-line

**Comment by mrlerch** [comment]
So, this means that the Magento Connect Manager does not work in this configuration that you so graciously provided? Or can it be enabled somehow. Or can extensions and addons only be installed via command line?

Please advise.

Thanks,

Martin

**Comment by magenx** [comment]
what exactly you need in Magento Connect Manager ??? you can even install extensions just from zip file http://ext.topmage.com/

**Comment by mrlerch** [comment]
Hello again and thank you for getting back to me. I am sorry, but I am new to Magento. Really trying it out, and I thought that the Connect Manager was  how one installs extensions. But apparently you can do all that with the command line. I will give that a try and thanks for all your help.

**Comment by rockdrigo** [comment]
its for the permissions, ammm u can see this
http://devdocs.magento.com/guides/m1x/install/installer-privileges_after.html#extensions

but the better option is use mage in CLI
happy coding :computer:

**Comment by mrlerch** [comment]
Ammm, thank you. But I know about the document you mentioned and the permissions are not the issue. The issue is that the index.php file is downloaded when accessed in the browser (storeurl/downloader/index.php) instead of parsed! I know that inside the magento.conf file for nginx there is this block:

    server {
    …
    ## Execute PHP scripts
    location ~  \.php$ {
        include /etc/nginx/conf.d/headers.conf;
        try_files $uri =404;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        ## Store code with multi domain
        #fastcgi_param MAGE_RUN_CODE $mage_code;
        #fastcgi_param MAGE_RUN_TYPE $mage_type;
        include fastcgi_params;
        }
    }

I am new to nginx but I believe this part of the .conf file for my store tells which .php files to parse. For some odd reason the files inside the /downloader (as well as other directories for that matter) are not executed. I think that this may pose a risk to allow others that know the magento file tree to download .php source files. Literally any .php file can be downloaded that is not in the root directory.


Any thoughts? How to tell php to execute all files in the root directory as well as all sub directories?

Thanks.

**Comment by magenx** [comment]
to make downloader work, you need to remove this location from nginx.
if you need to apply some rules to downloader location , then you need to add this location in to nginx config, and configure it to process separately.

something like this
```
location /downloader/ {
        allow 123.123.123.123;
        allow 123.123.123.123;
        deny all;
                location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/downloader/index.php;
        include /etc/nginx/fastcgi_params;
        }
}
```

but, the problem is, i dont understand why we all need this downloader, if in many cases it breaks extensions installation, and having extra entrance directly to your backend is insane...

**Comment by mrlerch** [comment]
Thank you for that. It looks like that this did the trick. I will keep it and lock it down with username / password authentication combined with allow from specific IP only. All the other locations that are locked down I will lock down with by IP and username / password as well. I thank you for the detailed information. This is by far the best script out there when it comes to Magento installation. Where can I read more about this set up and how to use Varnish and all the other stuff that was downloaded and installed?

Last but not least the script also downloaded and installed phpMyAdmin. Now the script obfuscated the installation directory name, but I would also like an additional IP number restriction in nginx config file for that directory. But when I add the phpMyAdmin directory to the access restricted directories by IP number and username and password, no the scripts won’t execute. And when I set it up as described for the downloader directory (below) then phpMyAdmin is still not running. Any suggestions?

Thanks,

Martin

**Comment by skazhikadyadya** [comment]
Hi, when i use mage in magento root folder:

```
-bash: ./mage: Permission denied
```
