### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by cloudswork-ruud** [magenx/MASC-M#17]
Hi,

Are you guys gonna release the Ubuntu version again? If not, can you share the old version with me?

Thanks in advance.

**Comment by magenx** [comment]
obviously we need to rewrite everything, because we never had one.  and we work with CentOS 7 optimization script now, CentOS 7 is very convenient and easy to maintain o.system. Administration so straightforward, especially comparing to 12.04 - 14.04. Ubuntu is ugly o.system.

**Comment by cloudswork-ruud** [comment]
I remember that I had an ubuntu version here in the past.
