### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by rockdrigo** [magenx/MASC-M#19]
the statick link autogenerated for magento 1.9.2.0
http://www.magentocommerce.com/downloads/assets/1.9.2.0/magento-1.9.2.0.tar.gz

dont work
how i can solve the problem???

thanks!

**Comment by magenx** [comment]
not sure whats going on with magento,
but for now we can only fall back to svn
```svn -q checkout http://svn.magentocommerce.com/source/branches/1.9 .```
