### ISSUE TITLE
Recommended Magento permissions don't seem to work in this setup

### ISSUE THREAD

**Issue by mrlerch** [magenx/MASC-M#21]
Hello, So I am somewhat new with this setup. In my case, the script sets the following permissions to the magento directory and it's sub directories:

find . -type f -exec chmod 664 {} \;
find . -type d -exec chmod 775 {} \;
chmod 777 -R var media

and in my case it sets the owner and group to: apache (FPM-User)

Now I looked at the latest Magento documentation:
http://devdocs.magento.com/guides/m1x/install/installer-privileges_after.html

And it states to do the following:
chown -R web-server-user-name . (which would be in this case nginx, even though I tried nginx, apache and root, but nothing worked)
and to put the following permissions:
find . -type f -exec chmod 400 {} \;
find . -type d -exec chmod 500 {} \; 
find var/ -type f -exec chmod 600 {} \; 
find media/ -type f -exec chmod 600 {} \;
find var/ -type d -exec chmod 700 {} \; 
find media/ -type d -exec chmod 700 {} \;

Again, when I set it to the recommended settings according to the Magento document I get a "File not found" or "Denied" error. 

Can someone please tell me which are the best permission settings for production environment, and the correct user.group ownership for all files inside the magento directory tree.

Thank you!

Martin

**Comment by magenx** [comment]
best permissions is when your php user and ftp users can write to any files and folders.
magento's recommended permissions look stupid...

**Comment by mrlerch** [comment]
Not only do they look stupid, they don't work for me - at all. :)
