### ISSUE TITLE
Question regarding URL Rewrites (nginx, Magento's URL Rewrite Management)

### ISSUE THREAD

**Issue by mrlerch** [magenx/MASC-M#23]
Hello again. Once more thank you so much for providing this fantastic script to get us little folks up and running with all these great tools available. You guys rock!!!

You are somewhat pre-configuring nginx config file for Magento install to use the URL Rewrite feature. URL rewrites when turned on inside Magento definitely work. They work for products and categories. However, I ran into an issue. I want to create under products and categories custom rewrites from old system URL (which is registered with Google and other search engines) to the new Magento product or category URL.

Here is what I did:
Go to Magento URL Rewrite Management
Click on "Add New"
Selected "For Product"
Then selected the category the product is in
Then under Request Path I saw: 
plastic-access-doors-and-access-panels/plastic-access-panel-4x6-non-hinged-34054.html
I replaced that with the product URL from the old store like so: 
products_retail/product_info.php?cPath=6&products_id=1

It shows then that Type is Custom, ID Path as product/1/5, and Target Path of catalog/product/view/id/1/category/5.

So technically when magentodomain.com/products_retail/product_info.php?cPath=6&products_id=1 comes in as a request it should redirect it to the new magento URL, right?

However it gives me a error 404 (it looks like the plain Nginx 404 not found page. Almost as if Magento does not even get a chance to translate the requested URL. 

Are there any additional redirect parameters that I have to add to the Nginx config file in order to get these "custom" Magento URL rewrites to work?

Any help you can give me is deeply appreciated. 

Sincerely,

Martin

**Comment by magenx** [comment]
there are two options, you have to use nginx rewrites, or create a script that will pass url rewrites from database to nginx for rewrite.

**Comment by mrlerch** [comment]
Ok.. so here is what I did in order to get the internal Magento rewrite feature to work on these custom items:
## Under this line in the nginx magento config file:

    location @rewrite {
        rewrite / /index.php?$args;
        }

## I added the location @missing below to allow advanced URL rewrites

location @missing {
    rewrite / /index.php;
}


And in this block here I added the line below my comment:

    ## Execute PHP scripts
    location ~  \.php$ {
        include /etc/nginx/conf.d/headers.conf;
        ##try_files $uri =404;
## I disabled the line above and added the 2 lines below
fastcgi_intercept_errors on;
try_files = $uri @missing;
        fastcgi_pass 127.0.0.1:9000;.....


Now it seems to be working as I think it should. Maybe it will help someone.
